name: Action workflow

on: [push]


jobs:
  
  run-github-actions:
  run-on: ubuntu-latest
 steps:
 - name:  Simple Javascript Action
 uses: actions/-world-javascript-action@v1 
 with:
 who-to-great: devopshint
 
 -name: Get the output time
 run: echo "${{ steps.hello.outputs.time }}"
