name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
         node-version: 16.14.0
         cache: "npm"
         cache-dependency-path: './server/package-lock.json'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: ng build --prod

    - name: Test
      run: ng test --watch=false
